#!/usr/bin/perl

use lib qw( ../lib );

use strict;
use warnings;

use Neko::HeatMap;
use Data::Dumper;
$Data::Dumper::Sortkeys = 1;   # Dumperdaten sortiert (sort) ausgeben

use Test::Simple tests => 1;

my $d = 1; # 0|1 Debugging

my $configFile = shift // '../t/TestConfig.conf';

my $HeatMap = new Neko::HeatMap( 'configFile' => $configFile );

my $Config = $HeatMap->getConfig();

print Dumper($Config) if $d;
print $Config->{'HeatMapUser'}{'language'}."\n" if $d;

if ( $HeatMap->hasErrors() ) {
    print "Fehler beim Config holen: \n". join("\n", @{ $HeatMap->hasErrors()} )."\n";
    ok ( 1 == 2 );
    exit 1;
}
else { 
    if ( $Config->{'HeatMapUser'}{'language'} eq 'de' ) {
        ok ( 1 == 1 ) ;
    }
    else {
        ok ( 1 == 2 );
        exit 2;
    }
}

exit 0;
